### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by elferherrera** [YS-L/csvlens#11] opened 2022-06-15 19:59 UTC
Is it planned to have horizontal scrolling?

**Comment by YS-L** [comment] 2022-08-07 17:09
Do you mean scrolling horizontally by one window instead of one column? I just added support for this in main branch.

**Comment by polarathene** [comment] 2024-05-12 11:58
`cargo install csvlens`, simple test file has an odd width set instead of what's available:

![image](https://github.com/YS-L/csvlens/assets/5098581/6bfc2ad8-609f-47c3-b3d2-3e12842dc135)

I was not able to scroll horizontally to view the contents of the third column "VALUE". Best I could manage was:
- Pressing TAB to switch to column selection mode which allowed for `>` to increase width.
- Typing `-` + `S` to toggle word wrap.
- TAB to cell selection mode and pressing ENTER to quit with that cell output to STDOUT.

The other keys that are meant to help scroll don't seem to work for me. This is with a Fedora 40 Docker container running on Ubuntu 22.04 (_via WSL2 on Windows Terminal_). So perhaps something with the environment is off 🤷‍♂️

**Comment by YS-L** [comment] 2024-05-13 17:03
@polarathene That is actually the expected behavior - horizontal scrolling here refers to scrolling the columns (e.g. showing more columns to the right) rather than scrolling the content within a column. The latter is not supported.

I'm curious whether the alternatives you mentioned work, or is there some reason they are not ideal? Feel free to open a new feature request.

**Comment by polarathene** [comment] 2024-05-15 12:02
> @polarathene That is actually the expected behavior

Is it also expected to truncate the third column there instead of using the available unused width? Did it reach an implicit max width for a column?

> I'm curious whether the alternatives you mentioned work, or is there some reason they are not ideal?

They work, but:
- `>` is rather tedious to increment the width, the line is quite long for the cell.
- I can't recall any issue with the wordwrap off the top of my head, other than it feeling a bit awkward (_I'm guessing this is vim/emacs inspired input, which I'm not familiar with_).
- Cell + ENTER ... well it takes me out of the viewer completely if I just wanted to see the full value and then check another cell.

I'd imagine that I could have pressed something to get a pop-over window rendered, overlaying the columns view to present the data in a more accessible manner, then return back to the column view to navigate to another cell and inspect that if the contents is quite long.

**Comment by YS-L** [comment] 2024-05-16 16:29
> Is it also expected to truncate the third column there instead of using the available unused width? Did it reach an implicit max width for a column?

Yes, there is an implicit max width to prevent any columns taking too much space, so that is expected. It can probably be improved though for cases like this where there are not many columns.

> They work, but:

Indeed, Cell + Enter was intended for piping out of csvlens rather than viewing the content. I was mainly curious about the first two options, but I think what you said makes sense. Previewing a truncated cell had been requested by other users before, so it's probably something that will be useful but is currently missing.

Previewing in a pop-over window is an interesting idea, thanks! To clarify, are you referring to some kind of overlay that is near the selected cell, or something like a modal at the center of the screen that switches the focus entirely to the content of that particular cell?

**Comment by YS-L** [comment] 2024-05-16 16:56
@polarathene  I opened a separate issue for this: https://github.com/YS-L/csvlens/issues/83

Feel free to leave your comments there. I will close this issue since this was about something else that should be resolved now. Thanks again!

**Closed by YS-L** 2024-05-16 16:56 UTC
